# Generated by Django 5.2.16 on 2026-08-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koru_stats', '0019_corphealthsnapshot_alter_general_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recluta_main_id', models.IntegerField(db_index=True, unique=True)),
                ('recluta_name', models.CharField(blank=True, default='', max_length=100)),
                ('reclutador_name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('ticket_numero', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Enlace de reclutamiento',
                'verbose_name_plural': 'Enlaces de reclutamiento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SocialEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_a_id', models.IntegerField(db_index=True)),
                ('main_b_id', models.IntegerField(db_index=True)),
                ('main_a_name', models.CharField(blank=True, default='', max_length=100)),
                ('main_b_name', models.CharField(blank=True, default='', max_length=100)),
                ('ventana', models.CharField(db_index=True, default='90d', max_length=20)),
                ('peso', models.IntegerField(default=0)),
                ('ultima_vez', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Arista social',
                'verbose_name_plural': 'Aristas sociales',
                'ordering': ['-peso'],
                'indexes': [models.Index(fields=['ventana', 'peso'], name='koru_edge_ventana_peso')],
                'constraints': [models.UniqueConstraint(fields=('main_a_id', 'main_b_id', 'ventana'), name='uniq_social_edge')],
            },
        ),
    ]
